### PR TITLE
Add extra CURLOPT support to `curl_fuzzer`

### PR DESCRIPTION
**Pull request by elopez**
This enhances `curl_fuzzer` with several new CURLOPTs, and improves fuzzing coverage.

### CODE REVIEW

**Comment by cmeister2** [comment]
This all looks great, to be honest; I can't find anything wrong with this. I assume it requires #61 to be in first and then this can be rebased on top.

**Comment by bagder** [comment]
I think #62 might be the preferable way.

**Comment by bagder** [comment]
but this PR works equally good/bad without that PR, so we can just as well merge this one first, can't we?

**Comment by cmeister2** [comment]
I'd rather not merge something that's failing the build unless I absolutely have to. I'll take another look at this this afternoon.

**Comment by elopez** [comment]
I have rebased the branch on the latest `master` so I'm hoping the CI should run fine now. If you need the previous branch I've [archived it here](https://github.com/trail-of-forks/curl-fuzzer/tree/elopez/curl-fuzzer-improvements-pre-rebase)

**Comment by bagder** [comment]
Lovely! :1st_place_medal:

**Pull request merged**
