### PR TITLE
fuzz_url.cc: fuzz the URL parser

### PR DESCRIPTION
**Pull request by bagder**
What else do we need to fuzz it?

### CODE REVIEW

**Comment by bagder** [comment]
I assume maybe we should somehow change the fourth argument's bitmask as well for better coverage.

**Comment by cmeister2** [comment]
You need to add a directory in corpora/ called `fuzz_url` with at least one test-case file in it otherwise `make check` can run forever, IIRC.

**Comment by cmeister2** [comment]
You also need to add this new fuzzer to `scripts/fuzz_targets`.

**Comment by cmeister2** [comment]
Other than those comments, the actual function of the fuzzer looks good!

**Comment by bagder** [comment]
@cmeister2 think we can merge this and see what happens?

**Review by cmeister2 — APPROVED** [review]
Go for it

**Pull request merged**
